---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LJKPC.
--- DateTime: 2024-09-20 15:42
---变量与常量

--变量
print("hello world")
name = "ljk"
age= 18
f= 1.5
print(name,age,f)

local a=1
function test()
    print(a)
end
test()

c=name..age..f
print(c)
print(type(name))
